Repository jenkinsci/aws-java-sdk2-plugin, pull requests merged in 2025-05, with the labels that each got.

#68 Add SSO module
  aws-java-sdk2-sso/pom.xml
  aws-java-sdk2-sso/src/main/resources/index.jelly
  pom.xml
Labels: enhancement

#67 Add netty-nio-client
  aws-java-sdk2-netty-nio-client/pom.xml
  aws-java-sdk2-netty-nio-client/src/main/resources/index.jelly
  pom.xml
Labels: enhancement

#75 Add missing exclusions
  aws-java-sdk2-netty-nio-client/pom.xml
Labels: skip-changelog

#76 Update plugin BOM
  aws-java-sdk2-netty-nio-client/pom.xml
  pom.xml
Labels: dependencies, java
